---
deployment:
  tasks:
    - export DEPLOYPATH=/home/glisapps/public_html/skatetests/
    - /bin/cp *.php $DEPLOYPATH
    - /bin/cp *.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R datafiles $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R jscript $DEPLOYPATH